import { Property, User } from './types';

export const mockProperties: Property[] = [
  {
    id: '1',
    name: 'Hotel Norrebro',
    location: '0.4 km from city centre',
    city: 'Copenhagen',
    country: 'Denmark',
    distanceFromCenter: '0.4 km',
    rating: 9.6,
    reviewCount: 1920,
    pricePerNight: 180,
    starRating: 3,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=400',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Private bathroom', 'Key card access', 'Free parking', '24-hour front desk', 'Free cancellation'],
    tags: ['Hot deal', 'Popular'],
    description: '3-star hotel located in the heart of Copenhagen',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: ['No pets allowed', 'No smoking', 'No partying'],
    rooms: [
      {
        id: 'r1',
        name: 'Double standard room',
        size: '28 sqm',
        capacity: 2,
        bedType: '1 queen bed or 2 separate beds',
        price: 180,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600',
        breakfastIncluded: true,
        refundable: false,
      },
      {
        id: 'r2',
        name: 'Comfort single room',
        size: '21 sqm',
        capacity: 1,
        bedType: '1 king size bed',
        price: 220,
        image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600',
        breakfastIncluded: true,
        refundable: false,
      },
      {
        id: 'r3',
        name: 'Double standard room',
        size: '25 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 250,
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600',
        breakfastIncluded: true,
        refundable: false,
      },
      {
        id: 'r4',
        name: 'Double fancy room',
        size: '25 sqm',
        capacity: 2,
        bedType: '1 king size bed and couch',
        price: 280,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600',
        breakfastIncluded: true,
        refundable: false,
      },
    ],
    reviews: [
      {
        id: 'rev1',
        author: 'Mark M.',
        rating: 10,
        date: '20 September, 2022',
        title: 'Excellent value for the price!',
        text: 'We enjoyed our stay at this hotel. We will definitely come back!',
        pros: ['Great location', 'Service', 'Bottle of champagne in the room!'],
        cons: [],
      },
      {
        id: 'rev2',
        author: 'Karina L.',
        rating: 5.6,
        date: '10 September, 2022',
        title: 'Good hotel but noisy location',
        text: 'Had room facing the street and it was super noisy. Unfortunately, we couldn\'t change room.',
        pros: [],
        cons: ['Noise'],
      },
    ],
  },
  {
    id: '2',
    name: 'Hotel Mitte',
    location: '1.7 km from city centre',
    city: 'Copenhagen',
    country: 'Denmark',
    distanceFromCenter: '1.7 km',
    rating: 9.2,
    reviewCount: 832,
    pricePerNight: 150,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Private bathroom', 'Free cancellation'],
    tags: ['Hot deal'],
    description: '4-star hotel in Copenhagen',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: ['No pets allowed', 'No smoking'],
    rooms: [
      {
        id: 'r5',
        name: 'Standard room',
        size: '25 sqm',
        capacity: 2,
        bedType: '1 queen size bed',
        price: 150,
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600',
        breakfastIncluded: false,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev3',
        author: 'Sarah K.',
        rating: 9.0,
        date: '15 October, 2022',
        title: 'Great stay, would recommend',
        text: 'Nice hotel with good amenities. The location is convenient.',
        pros: ['Clean rooms', 'Good service'],
        cons: [],
      },
    ],
  },
  {
    id: '3',
    name: 'Hotel ZOO Copenhagen',
    location: '2.0 km from city centre',
    city: 'Copenhagen',
    country: 'Denmark',
    distanceFromCenter: '2.0 km',
    rating: 8.0,
    reviewCount: 1000,
    pricePerNight: 220,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
    images: [
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
    ],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Private bathroom', 'Free cancellation'],
    tags: ['Popular'],
    description: '4-star hotel in Copenhagen',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: ['No pets allowed'],
    rooms: [
      {
        id: 'r6',
        name: 'Premium room',
        size: '30 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 220,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600',
        breakfastIncluded: false,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev4',
        author: 'John D.',
        rating: 8.5,
        date: '5 November, 2022',
        title: 'Comfortable and clean',
        text: 'Good value for money. The rooms are spacious and well-maintained.',
        pros: ['Spacious rooms', 'Good value'],
        cons: ['Limited parking'],
      },
    ],
  },
  {
    id: '4',
    name: 'Hotel Bonduel',
    location: '2.2 km from city centre',
    city: 'Copenhagen',
    country: 'Denmark',
    distanceFromCenter: '2.2 km',
    rating: 6.3,
    reviewCount: 200,
    pricePerNight: 60,
    starRating: 2,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
    ],
    amenities: [],
    tags: ['Hot deal', 'Popular'],
    description: '2-star hotel in Copenhagen',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [
      {
        id: 'r7',
        name: 'Comfort room',
        size: '20 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 60,
        image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600',
        breakfastIncluded: false,
        refundable: false,
      },
    ],
    reviews: [],
  },
  {
    id: '5',
    name: 'Soho Hotel London',
    location: '0.5 km from city centre',
    city: 'London',
    country: 'United Kingdom',
    distanceFromCenter: '0.5 km',
    rating: 9.6,
    reviewCount: 2500,
    pricePerNight: 130,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800',
    images: [],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Private bathroom'],
    tags: ['Popular'],
    description: '4-star hotel in London',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [
      {
        id: 'r8',
        name: 'Standard room',
        size: '25 sqm',
        capacity: 2,
        bedType: '1 queen size bed',
        price: 130,
        image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600',
        breakfastIncluded: false,
        refundable: true,
      },
      {
        id: 'r9',
        name: 'Deluxe room',
        size: '35 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 180,
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [],
  },
  {
    id: '6',
    name: 'Sunset Plaza Hotel',
    location: '1.0 km from city centre',
    city: 'Barcelona',
    country: 'Spain',
    distanceFromCenter: '1.0 km',
    rating: 9.8,
    reviewCount: 3200,
    pricePerNight: 210,
    starRating: 5,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    images: [],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Private bathroom', 'Spa'],
    tags: ['Popular'],
    description: '5-star hotel in Barcelona',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [
      {
        id: 'r10',
        name: 'Luxury suite',
        size: '50 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 210,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r11',
        name: 'Premium suite',
        size: '60 sqm',
        capacity: 3,
        bedType: '1 king size bed and sofa bed',
        price: 280,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r12',
        name: 'Presidential suite',
        size: '80 sqm',
        capacity: 4,
        bedType: '1 king size bed and 2 single beds',
        price: 350,
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [],
  },
  {
    id: '7',
    name: 'Three Quarters Hotel',
    location: '0.8 km from city centre',
    city: 'Lisbon',
    country: 'Portugal',
    distanceFromCenter: '0.8 km',
    rating: 9.5,
    reviewCount: 1800,
    pricePerNight: 130,
    starRating: 3,
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
    images: [],
    amenities: ['Free Wi-Fi', 'Air conditioning'],
    tags: [],
    description: '3-star hotel in Lisbon',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [],
    reviews: [],
  },
  {
    id: '8',
    name: 'Surf\'n Turf Suites',
    location: '2.5 km from city centre',
    city: 'Bratislava',
    country: 'Slovakia',
    distanceFromCenter: '2.5 km',
    rating: 9.5,
    reviewCount: 950,
    pricePerNight: 70,
    starRating: 3,
    image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
    images: [
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=400',
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Free parking'],
    tags: [],
    description: '3-star hotel in Bratislava',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [
      {
        id: 'r13',
        name: 'Standard room',
        size: '22 sqm',
        capacity: 2,
        bedType: '1 queen size bed',
        price: 70,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600',
        breakfastIncluded: false,
        refundable: false,
      },
      {
        id: 'r14',
        name: 'Comfort room',
        size: '28 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 90,
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600',
        breakfastIncluded: true,
        refundable: false,
      },
    ],
    reviews: [
      {
        id: 'rev5',
        author: 'Emma W.',
        rating: 7.5,
        date: '1 December, 2022',
        title: 'Decent budget option',
        text: 'Basic but clean. Good for a short stay.',
        pros: ['Affordable', 'Clean'],
        cons: ['Small rooms', 'Noisy'],
      },
    ],
  },
  {
    id: '9',
    name: 'Hotel Apple',
    location: '0.6 km from city centre',
    city: 'Copenhagen',
    country: 'Denmark',
    distanceFromCenter: '0.6 km',
    rating: 8.3,
    reviewCount: 792,
    pricePerNight: 260,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800',
    images: [],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Free airport shuttle', 'Breakfast included'],
    tags: ['Hot deal'],
    description: '4-star hotel in Copenhagen',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [
      {
        id: 'r15',
        name: 'Standard room',
        size: '30 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 260,
        image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r16',
        name: 'Superior room',
        size: '35 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 300,
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r17',
        name: 'Executive suite',
        size: '45 sqm',
        capacity: 2,
        bedType: '1 king size bed and sitting area',
        price: 380,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev6',
        author: 'Michael B.',
        rating: 9.8,
        date: '20 November, 2022',
        title: 'Luxury experience',
        text: 'Exceptional service and beautiful rooms. The spa is amazing!',
        pros: ['Luxury amenities', 'Excellent service', 'Great spa'],
        cons: [],
      },
      {
        id: 'rev7',
        author: 'Lisa T.',
        rating: 9.2,
        date: '10 November, 2022',
        title: 'Perfect location',
        text: 'Beautiful hotel in a great location. Highly recommend!',
        pros: ['Perfect location', 'Beautiful design'],
        cons: [],
      },
    ],
  },
  {
    id: '10',
    name: 'Hotel Little Mermaid',
    location: '2.0 km from city centre',
    city: 'Copenhagen',
    country: 'Denmark',
    distanceFromCenter: '2.0 km',
    rating: 9.5,
    reviewCount: 2000,
    pricePerNight: 420,
    starRating: 5,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    images: [],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Breakfast included', 'Spa'],
    tags: ['Popular', 'Rare find'],
    description: '5-star hotel in Copenhagen',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [
      {
        id: 'r18',
        name: 'Deluxe suite',
        size: '55 sqm',
        capacity: 2,
        bedType: '1 king size bed',
        price: 420,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r19',
        name: 'Presidential suite',
        size: '75 sqm',
        capacity: 3,
        bedType: '1 king size bed and sofa bed',
        price: 550,
        image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r20',
        name: 'Royal suite',
        size: '100 sqm',
        capacity: 4,
        bedType: '1 king size bed and 2 single beds',
        price: 750,
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [],
  },
  {
    id: '11',
    name: 'Hostel Bekpek',
    location: '2.2 km from city centre',
    city: 'Copenhagen',
    country: 'Denmark',
    distanceFromCenter: '2.2 km',
    rating: 6.4,
    reviewCount: 840,
    pricePerNight: 44,
    starRating: 1,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
    images: [],
    amenities: ['Free Wi-Fi', 'Breakfast included'],
    tags: ['Budget'],
    description: 'Backpacker hostel in Copenhagen',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: [],
    rooms: [
      {
        id: 'r21',
        name: 'Dormitory bed',
        size: 'Shared room',
        capacity: 1,
        bedType: '1 bunk bed',
        price: 44,
        image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600',
        breakfastIncluded: true,
        refundable: false,
      },
      {
        id: 'r22',
        name: 'Private room',
        size: '15 sqm',
        capacity: 2,
        bedType: '1 queen size bed',
        price: 80,
        image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600',
        breakfastIncluded: true,
        refundable: false,
      },
    ],
    reviews: [
      {
        id: 'rev8',
        author: 'Tom R.',
        rating: 6.8,
        date: '25 October, 2022',
        title: 'Basic hostel experience',
        text: 'It\'s a hostel, so expectations should be set accordingly. Clean and functional.',
        pros: ['Budget-friendly', 'Breakfast included'],
        cons: ['Shared facilities', 'Noisy'],
      },
    ],
  },

  // --- NEW ENTRIES ADDED BELOW ---

  {
    id: '12',
    name: 'Le Petit Palais',
    location: '0.3 km from city centre',
    city: 'Paris',
    country: 'France',
    distanceFromCenter: '0.3 km',
    rating: 9.4,
    reviewCount: 1540,
    pricePerNight: 240,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1505691723518-36a4c9d6e9a4?w=800',
    images: [
      'https://images.unsplash.com/photo-1505691723518-36a4c9d6e9a4?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
      'https://images.unsplash.com/photo-1523301343968-9f1b057f5b3b?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Breakfast included', 'Concierge', 'Bar', 'Laundry service'],
    tags: ['Popular', 'City centre'],
    description: 'Charming 4-star boutique hotel near the Louvre and the Seine.',
    checkInTime: '2 PM',
    checkOutTime: '12 PM',
    houseRules: ['No smoking', 'No pets'],
    rooms: [
      {
        id: 'r23',
        name: 'Classic double',
        size: '24 sqm',
        capacity: 2,
        bedType: '1 queen bed',
        price: 240,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r24',
        name: 'Superior double',
        size: '30 sqm',
        capacity: 3,
        bedType: '1 king bed and sofa bed',
        price: 320,
        image: 'https://images.unsplash.com/photo-1523301343968-9f1b057f5b3b?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev9',
        author: 'Claire P.',
        rating: 9.6,
        date: '12 March, 2023',
        title: 'Lovely location and friendly staff',
        text: 'Close to major attractions; staff helped with restaurant bookings.',
        pros: ['Location', 'Helpful staff'],
        cons: [],
      },
    ],
  },
  {
    id: '13',
    name: 'Olympia Roma',
    location: '1.2 km from city centre',
    city: 'Rome',
    country: 'Italy',
    distanceFromCenter: '1.2 km',
    rating: 8.9,
    reviewCount: 980,
    pricePerNight: 160,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1543349686-0b0ecb5b1d4b?w=800',
    images: [
      'https://images.unsplash.com/photo-1543349686-0b0ecb5b1d4b?w=800',
      'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Air conditioning', 'Rooftop bar', 'Airport shuttle'],
    tags: ['Rooftop', 'Good value'],
    description: 'Stylish 4-star hotel with a rooftop bar and easy access to public transport.',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: ['No smoking'],
    rooms: [
      {
        id: 'r25',
        name: 'Classic double',
        size: '26 sqm',
        capacity: 2,
        bedType: '1 queen bed',
        price: 160,
        image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600',
        breakfastIncluded: false,
        refundable: true,
      },
      {
        id: 'r26',
        name: 'Family room',
        size: '40 sqm',
        capacity: 4,
        bedType: '1 king bed and 2 single beds',
        price: 260,
        image: 'https://images.unsplash.com/photo-1543349686-0b0ecb5b1d4b?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev10',
        author: 'Luca R.',
        rating: 8.8,
        date: '7 April, 2023',
        title: 'Great rooftop views',
        text: 'Rooftop bar had excellent views and cocktails.',
        pros: ['Rooftop bar', 'Central location'],
        cons: [],
      },
    ],
  },
  {
    id: '14',
    name: 'Berlin Central Suites',
    location: '0.9 km from city centre',
    city: 'Berlin',
    country: 'Germany',
    distanceFromCenter: '0.9 km',
    rating: 9.1,
    reviewCount: 1210,
    pricePerNight: 140,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=800',
    images: [
      'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=800',
      'https://images.unsplash.com/photo-1488747279002-c8523379faaa?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Gym', 'Breakfast included', 'Laundry service'],
    tags: ['Business friendly'],
    description: 'Modern suites optimized for business travellers with fast Wi-Fi and a small gym.',
    checkInTime: '2 PM',
    checkOutTime: '12 PM',
    houseRules: ['No pets allowed'],
    rooms: [
      {
        id: 'r27',
        name: 'Business suite',
        size: '32 sqm',
        capacity: 2,
        bedType: '1 king bed',
        price: 140,
        image: 'https://images.unsplash.com/photo-1488747279002-c8523379faaa?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r28',
        name: 'Executive suite',
        size: '45 sqm',
        capacity: 3,
        bedType: '1 king bed and sofa bed',
        price: 200,
        image: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev11',
        author: 'Anna S.',
        rating: 9.0,
        date: '20 May, 2023',
        title: 'Ideal for work trips',
        text: 'Fast Wi-Fi and quiet rooms — perfect for business travel.',
        pros: ['Fast Wi-Fi', 'Comfortable workspace'],
        cons: [],
      },
    ],
  },
  {
    id: '15',
    name: 'Hudson Midtown Hotel',
    location: '1.1 km from city centre',
    city: 'New York',
    country: 'United States',
    distanceFromCenter: '1.1 km',
    rating: 8.7,
    reviewCount: 4100,
    pricePerNight: 320,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800',
    images: [
      'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800',
      'https://images.unsplash.com/photo-1501117716987-c8e5b78a3e9b?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Gym', 'Breakfast included', '24-hour front desk', 'Pet friendly'],
    tags: ['Central', 'Pet friendly'],
    description: 'Stylish Midtown hotel close to theaters and subway links.',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: ['Pets allowed', 'No smoking'],
    rooms: [
      {
        id: 'r29',
        name: 'City view room',
        size: '28 sqm',
        capacity: 2,
        bedType: '1 queen bed',
        price: 320,
        image: 'https://images.unsplash.com/photo-1501117716987-c8e5b78a3e9b?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
      {
        id: 'r30',
        name: 'Family suite',
        size: '50 sqm',
        capacity: 4,
        bedType: '2 queen beds',
        price: 480,
        image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev12',
        author: 'James K.',
        rating: 8.5,
        date: '1 June, 2023',
        title: 'Great location',
        text: 'Walking distance to Broadway and multiple subway lines.',
        pros: ['Location', 'Spacious rooms'],
        cons: ['Pricey breakfast'],
      },
    ],
  },
  {
    id: '16',
    name: 'Shinjuku Garden Hotel',
    location: '0.6 km from city centre',
    city: 'Tokyo',
    country: 'Japan',
    distanceFromCenter: '0.6 km',
    rating: 9.3,
    reviewCount: 880,
    pricePerNight: 190,
    starRating: 4,
    image: 'https://images.unsplash.com/photo-1549692520-acc6669e2f0c?w=800',
    images: [
      'https://images.unsplash.com/photo-1549692520-acc6669e2f0c?w=800',
      'https://images.unsplash.com/photo-1519821172141-b5d8b6b6d5b4?w=400',
    ],
    amenities: ['Free Wi-Fi', 'Breakfast included', 'On-site restaurant', 'Baggage storage'],
    tags: ['Near metro'],
    description: 'Comfortable hotel situated close to Shinjuku station and parks.',
    checkInTime: '3 PM',
    checkOutTime: '11 AM',
    houseRules: ['No smoking'],
    rooms: [
      {
        id: 'r31',
        name: 'Compact double',
        size: '20 sqm',
        capacity: 2,
        bedType: '1 double bed',
        price: 140,
        image: 'https://images.unsplash.com/photo-1519821172141-b5d8b6b6d5b4?w=600',
        breakfastIncluded: false,
        refundable: true,
      },
      {
        id: 'r32',
        name: 'Japanese style room',
        size: '30 sqm',
        capacity: 3,
        bedType: 'Futon + 1 single bed',
        price: 220,
        image: 'https://images.unsplash.com/photo-1549692520-acc6669e2f0c?w=600',
        breakfastIncluded: true,
        refundable: true,
      },
    ],
    reviews: [
      {
        id: 'rev13',
        author: 'Miho T.',
        rating: 9.2,
        date: '18 July, 2023',
        title: 'Clean and convenient',
        text: 'Very close to the station and quiet at night.',
        pros: ['Location', 'Cleanliness'],
        cons: [],
      },
    ],
  },
];

export const popularDestinations = [
  { name: 'Spain', image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600', city: 'Barcelona' },
  { name: 'London', image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600', city: 'London' },
  { name: 'Lisbon', image: 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=600', city: 'Lisbon' },
  { name: 'Croatia', image: 'https://images.unsplash.com/photo-1533613220915-609f661a6fe1?w=600', city: 'Dubrovnik' },
  { name: 'Bratislava', image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600', city: 'Bratislava' },
  { name: 'Copenhagen', image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=600', city: 'Copenhagen' },
  // Added a few more popular destinations
  { name: 'Paris', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600', city: 'Paris' },
  { name: 'Rome', image: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=600', city: 'Rome' },
  { name: 'Tokyo', image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?w=600', city: 'Tokyo' },
];

export const mockUser: User = {
  id: '1',
  name: 'Maria Lost',
  email: 'maria@lostpost.de',
  location: 'Hamburg, Germany',
  nationality: 'German',
  dateOfBirth: '06/11/1988',
};
